{"uuid": "6cfcb8cf-2503-4841-9369-0f8b9b28ac4d", "children": ["501f6024-cbdb-49d4-8add-664198c668cf"], "befores": [{"name": "start_system", "status": "broken", "statusDetails": {"message": "KeyError: 'USERNAME'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/src/code/test_cases/base_case.py\", line 17, in start_system\n    self.api_client = ApiClient(os.environ['USERNAME'], os.environ['PASSWORD'])\n  File \"/usr/local/lib/python3.8/os.py\", line 675, in __getitem__\n    raise KeyError(key) from None\n"}, "start": 1647891518360, "stop": 1647891518366}], "start": 1647891518360, "stop": 1647891518384}